### ISSUE TITLE
Check for bad sensors

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-qa-dashboard#14]
Check for unexpected `NA`s for measured variables.  Not the same as #2

**Comment by Aariq** [comment]
It looks like Ft Mohave CA, Mohave-2, Wellton ETo, and Yuma Valley ETo don't have soil temperature probes so missing values there shouldn't trigger a QA warning.  Is that correct @jeremylweiss?

**Comment by jeremylweiss** [comment]
That is correct @Aariq 

Also, Wellton ETo and Yuma Valley ETo do not have precipitation measurements
