### ISSUE TITLE
New battery analytics tab

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-qa-dashboard#22]
- [ ] Create a new page to explore relationships between voltage and weather (sunlight, temperature, etc.)
- [x] Add checks for voltage thresholds (https://azmet.arizona.edu/azmet/data/00volts.htm)
- [x] Add checks for net change in voltage over prev 10 days

**Comment by Aariq** [comment]
@jeremylweiss Should the voltage checks apply to just hourly data or both hourly and daily? Let's talk more about the battery stuff on Friday.

**Comment by jeremylweiss** [comment]
Both, please. Hourly values are averages of all every-10-seconds scans during that hour. Daily maximums and minimums, however, are based on all scans that day and would register any fleeting spikes or drops. Such spikes and drops, which could foretell problems, would be washed out in hourly average values.

**Comment by Aariq** [comment]
Would you prefer the voltage range checks to be added to the existing tables for daily and hourly validations, or would you prefer a new tab with all the battery-related stuff (validations and visualizations) in one place?

**Comment by jeremylweiss** [comment]
Let's please go with a new tab. Thanks!

**Comment by jeremylweiss** [comment]
Theoretical solar model from legacy site included elevation and latitude as inputs, apparently: 
https://cales.arizona.edu/azmet/data/00solar.txt

**Comment by Aariq** [comment]
Ok, battery tab is live! Let me know if you have any issues with it.

-Eric

**Comment by jeremylweiss** [comment]
Great, thanks!
