### ISSUE TITLE
add `na.rm = TRUE` to battery validation tests

### ISSUE THREAD

**Issue by jeremylweiss** [uace-azmet/azmet-qa-dashboard#37]
`NA`s show up when testing for value thresholds. Confirm that missing data are checked for somewhere else on dashboard

**Comment by Aariq** [comment]
Do you happen to know what dates you were seeing missing data for battery voltage for?  I think this is an easy fix, but wanted to double-check that it worked.

**Comment by jeremylweiss** [comment]
9/14 : Desert Ridge
9/13 : Desert Ridge
6/22 : Yuma Valley ETo
5/3 : Paloma
5/2 : Paloma
