### ISSUE TITLE
Different tables for `validation` and `reporting` information

### ISSUE THREAD

**Issue by jeremylweiss** [uace-azmet/azmet-qa-dashboard#43]
In the Validation panel, we currently list together results from both `validation` of values from measured variables and `reporting` of data from individual stations. These two groups may be different enough in terms of the information they convey, and may be better presented if they were split between Validation and Reporting panels (or, sub-panels within the existing panel).

**Comment by Aariq** [comment]
Maybe just two separate tables with titles like "Data Validation" and "Sensor Reporting", like we now see in the Validation section of the Battery tab?

**Comment by jeremylweiss** [comment]
Yes, good idea! That would work, with table titles "Data Reporting" and "Data Values", in that order.
