### ISSUE TITLE
Set upper bounds for solar radiation based on DOY and location

### ISSUE THREAD

**Issue by Aariq** [uace-azmet/azmet-qa-dashboard#5]
This is determined by stuff like where the sun is relative to the earth.  The max solar radiation for a location and DOY should be knowable.

**Comment by Aariq** [comment]
Could also be useful for a dirty sensor.  E.g. if it's not raining and solar radiaion is x ammount below theoritcal max, flag the data

**Comment by Aariq** [comment]
Getting closer!

Hourly (in April 2022)
![Image](https://github.com/uace-azmet/azmet-qa-dashboard/assets/25404783/6a00e86b-ce26-4679-9646-21f133b9464c)

Daily (2022)

![Image](https://github.com/uace-azmet/azmet-qa-dashboard/assets/25404783/ccd328fc-9b22-4828-9b3f-6e02515e45d5)

Not totally sure why sensor data is going beyond estimated theoretical max in some times of year.   There are a few parameters that are set with some assumptions (e.g. vertically integrated water vapor concentration, visibility), but adjusting these within reason doesn't seem to make noticeable impacts.  Might need to stick with this model and just flag data that is above the estimated max by some arbitrary amount.

**Comment by Aariq** [comment]
Other R packages:

- https://github.com/bnasr/solrad
- https://github.com/trenchproject/TrenchR

Resources:

- https://emf-creaf.github.io/meteolandbook/solarradiation.html

**Comment by Aariq** [comment]
@jeremylweiss do you have elevation for the sites? (forgive me if I've asked this before)

**Comment by jeremylweiss** [comment]
Yes, will send it over

**Comment by Aariq** [comment]
The functions in the `TrenchR` package do a great job and are much easier to use, so thanks for finding that.  My calculations still underestimate the total solar radiation in mornings and evenings and I now understand why.  All of these packages estimate instantaneous solar radiation (W/m^2) and I've been converting it to total solar radiation just by multiplying by 1 hr.  That assumption works in the middle of the day because assuming the slice of the instantaneous solar radiation curve is a rectangle (1 hr width * solar radiation at the midpoint height) is close enough.  However, because of the shape of that curve in the mornings and evenings, this rectangle calculation underestimates the actual area under the curve.  This feels like a geometry/calculus problem that there is a better solution for, so maybe I'll take a _lilttle_ more time on this before giving up and just setting the threshold for error at my estimate + 10% or whatever.
![Quick sheets - page 260](https://github.com/uace-azmet/azmet-qa-dashboard/assets/25404783/0d58e13e-0b11-4892-b446-4acd3f2189e4)

**Comment by Aariq** [comment]
I guess I just need to use a smaller ∆x 🤦‍♂️.  I'll try estimating instantaneous solar radiation every 15 min and summing it for each hour and see if that's close enough.  Might still have to add a bit of a "buffer" before a validation failure is triggered.  Just thinking outloud here.

**Comment by jeremylweiss** [comment]
Ah yes, good ol' calculus . . . it's been a long while, but you're helping me recall the ∆x approach!

**Comment by Aariq** [comment]
No... that's not quite it.  The observed curves (black) are still wider than the theoretical curves (red) I'm calculating even if I integrate over each hour using 2 min increments.  This theoretical curve includes direct, diffuse, and reflected radiation and assumes a 100% atmospheric transmissivity and 100% albedo. 

![Image](https://github.com/uace-azmet/azmet-qa-dashboard/assets/25404783/623185af-0f23-4bff-be95-7c42ef4ccd48)

Perhaps I'm missing something in my understanding of what exactly the sensors are measuring and reporting?

**Comment by dlebauer** [comment]
> missing something in my understanding of what exactly the sensors are measuring and reporting?

not sure if this is relevant but I'll point out that the solar spectrum changes throughout the day; the sensitivity of the sensor does not.

![image](https://github.com/uace-azmet/azmet-qa-dashboard/assets/464871/b1bdec15-9481-43e6-a992-2ec10e9c139c)

See also

https://www.campbellsci.com/li200r-l
https://s.campbellsci.com/documents/us/product-brochures/b_li200r.pdf

**Comment by Aariq** [comment]
While trying to make a reprex to share with the TrenchR folks, I somehow solved my own problem.  I'm honestly not quite sure what I was doing wrong yet, but re-writing the code in a fresh .R file seems to have fixed it somehow 🤣.

![Screenshot 2023-10-05 at 12 45 01 PM](https://github.com/uace-azmet/azmet-qa-dashboard/assets/25404783/ca0668a3-c42d-4da3-a258-f85fc3993258)

There's a little blip where observed data is *slightly* above predicted, but I'm solving that by adding a tolerance to the validation function that will allow you to ignore small differences.

**Comment by jeremylweiss** [comment]
That's happened to me before, too, more times than I can remember. Nothing like a just-start-from-scratch solution! 🤣
